# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14dd8a89f43e9e6b6f7c26ac21bb29734175222b515fbae5724678b5b8d3432b52f919a05f73516dc61507944655b2f69d118651a0793cf287c5b76a53bfc8e9

test:
  secret_key_base: 09660dac683819249b054c34eccdb1749e8649f5ca9ce9389d7589f32411d9b4d54cf51157e450c739ff3b15542e1be2e52f5d75cd5de59d891d88e424235d39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
